version: '3.10'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-dev
    user: root
    ports:
      - "8084:8080"
      - "50003:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge
