version: '3.10'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock  # 👈 Mount host Docker socket
    privileged: true  # 👈 Allow docker-in-docker
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge
